version: '3.3'

volumes:
  share:
  caddy_data:
  caddy_config:
  postgis-data:
  shiny-apps:

services:

  caddy:
    container_name: caddy
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /share:/share   

  rstudio:
    container_name: rstudio
    build: ./rstudio-shiny
    image: bdbest/rstudio-shiny:ws
    volumes:
      - shiny-apps:/srv/shiny-server
      - share:/share
    restart: unless-stopped
    environment:
      ROOT: 'true'
      USER: admin
      PASSWORD: $PASSWORD
      ADD: shiny
    ports:
      - 8787:8787 # rstudio.
      - 3838:3838 # shiny.
      - 8888:8888 # api.

  postgis:
    container_name: postgis
    image: postgis/postgis:latest
    environment:
      POSTGRES_DBNAME: gis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: $PASSWORD
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./postgis/postgresql.conf:/etc/postgresql/postgresql.conf
      - share:/share
    restart: unless-stopped
    healthcheck:
      test: 'exit 0'
    ports:
      - 5432:5432

  tileserv:
    container_name: tileserv
    environment:
      DATABASE_URL: postgres://admin:$PASSWORD@postgis:5432/gis
      # config: https://github.com/CrunchyData/pg_tileserv#configuration-file
      MaxFeaturesPerTile: -1 # Limit number of features requested (-1 = no limit; default: 10000)
      CacheTTL: 600          # matching with tilecache's default_ttl below
    image: pramsey/pg_tileserv:latest
    build:
      context: ./pg_tileserv
      dockerfile: Dockerfile.alpine
      args:
        VERSION: latest
    depends_on:
      - postgis
    ports:
      - 7800:7800
      
  tilecache:
    container_name: tilecache
    image: eeacms/varnish
    ports:
      - 6081:6081 # tile.
    environment:
      BACKENDS: "tileserv:7800"
      DNS_ENABLED: "false"
      COOKIES: "true"
      PARAM_VALUE: "-p default_ttl=600" # 600 sec = 10 min * 60 sec/min
    depends_on:
      - tileserv
      
  featureserv:
    container_name: featureserv
    environment:
      DATABASE_URL: postgres://admin:$PASSWORD@postgis:5432/gis
      # config: https://access.crunchydata.com/documentation/pg_featureserv/1.2.0/installation/configuration/
      LimitMax: 1000000
    image: pramsey/pg_featureserv:latest # https://github.com/CrunchyData/pg_featureserv
    depends_on:
      - postgis
    ports:
      - 9000:9000

