version: '3.3'

volumes:
  postgis-backups:
  geoserver-data:
  postgis-data:
  mysql-data:
  shiny-apps:

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    environment:
      DEFAULT_HOST: wp.ships4whales.org
      VIRTUAL_HOST_SPECIFIC_PORT: 'true'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/nginx.tmpl:/app/nginx.tmpl:ro
    restart: on-failure
    ports:
      - 80

  postgis:
    image: kartoza/postgis:11.0-2.5
    environment:
      POSTGRES_DBNAME: gis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${PASSWORD}"
    volumes:
      - postgis-data:/var/lib/postgresql
    restart: on-failure
    healthcheck:
      test: 'exit 0'
    ports:
      - 5432
      
  postgis-backup:
    image: kartoza/pg-backup:11.0
    volumes:
      - postgis-backups:/backups
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: gis
      POSTGRES_USER: admin
      POSTGRES_PASS: "${PASSWORD}"
      DUMPPREFIX: PG_gis
    restart: on-failure
    depends_on:
      - postgis
      
  geoserver:
    image: kartoza/geoserver:2.15.2
    environment:
      VIRTUAL_HOST: geoserver.ships4whales.org    
      USERNAME: admin
      PASS: "${PASSWORD}"
      GEOSERVER_ADMIN_PASSWORD: "${PASSWORD}"
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - 8080
    restart: on-failure
    depends_on:
      - postgis
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0.18
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: "${PASSWORD}"
    ports:
      - 3306
       
  wordpress:
    depends_on:
      - mysql
    image: wordpress:php7.4-apache
    ports:
      - 9000
    restart: always
    environment:
      VIRTUAL_HOST: wp.ships4whales.org
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: "${PASSWORD}"
      WORDPRESS_DB_NAME: wordpress

  rstudio-shiny:
    build: ./rstudio-shiny
    image: bdbest/rstudio-shiny:s4w
    volumes:
      - shiny-apps:/srv/shiny-server
    restart: always
    environment:
      VIRTUAL_HOST: rstudio.ships4whales.org:8787,shiny.ships4whales.org:3838
      ROOT: 'true'
      USER: admin
      PASSWORD: "${PASSWORD}" 
    expose:
      - 8787
      - 3838



 